import { PrismaClient, ScholarshipType, DegreeLevel } from '@prisma/client'

const prisma = new PrismaClient()

async function main() {
  console.log('🌱 Seeding scholarships database...')

  // Create sample scholarships
  const scholarships = [
    {
      name: "Mastercard Foundation Scholars Program",
      provider: "Mastercard Foundation",
      country: "Multiple Countries",
      amount: 100000,
      currency: "USD",
      type: ScholarshipType.FULL,
      description: "The Mastercard Foundation Scholars Program is a global initiative that provides comprehensive scholarship support to academically talented yet economically disadvantaged young people, particularly from Africa.",
      eligibility: "Must be a citizen of an African country, demonstrate financial need, show academic excellence, and have leadership potential.",
      deadline: new Date("2025-03-31"),
      applicationOpenDate: new Date("2024-11-01"),
      website: "https://mastercardfdn.org/all/scholars/",
      applicationLink: "https://apply.mastercardfdn.org",
      contactEmail: "scholars@mastercardfdn.org",
      fieldOfStudy: ["Engineering", "Business", "Agriculture", "Health Sciences", "Technology"],
      degreeLevel: [DegreeLevel.BACHELOR, DegreeLevel.MASTER],
      minGPA: 3.5,
      maxAge: 29,
      forWomen: false,
      forAfrican: true,
      forUnderrepresented: true,
      targetCountries: ["Kenya", "Ghana", "Nigeria", "Rwanda", "Senegal", "Uganda", "Ethiopia", "South Africa"],
      requiresIELTS: true,
      minIELTS: 6.5,
      requiresTOEFL: true,
      minTOEFL: 79,
      numberOfAwards: 100,
      renewableYears: 4,
      coversTuition: true,
      coversLiving: true,
      coversTravel: true,
      coversBooks: true,
      featured: true,
      verified: true,
    },
    {
      name: "African Women in STEM Scholarship",
      provider: "African Union Commission",
      country: "Pan-African",
      amount: 50000,
      currency: "USD",
      type: ScholarshipType.FULL,
      description: "Empowering African women to pursue careers in Science, Technology, Engineering, and Mathematics through comprehensive scholarship support.",
      eligibility: "Female students from African countries pursuing STEM degrees at recognized universities.",
      deadline: new Date("2025-05-15"),
      applicationOpenDate: new Date("2025-01-01"),
      website: "https://au.int/en/stem-women",
      fieldOfStudy: ["Engineering", "Computer Science", "Mathematics", "Physics", "Chemistry", "Biology"],
      degreeLevel: [DegreeLevel.BACHELOR, DegreeLevel.MASTER, DegreeLevel.PHD],
      minGPA: 3.0,
      maxAge: 35,
      forWomen: true,
      forAfrican: true,
      targetCountries: [], // All African countries
      requiresIELTS: true,
      minIELTS: 6.0,
      numberOfAwards: 50,
      coversTuition: true,
      coversLiving: true,
      coversTravel: true,
      featured: true,
      verified: true,
    },
    {
      name: "Mandela Rhodes Scholarship",
      provider: "Mandela Rhodes Foundation",
      country: "South Africa",
      amount: 30000,
      currency: "USD",
      type: ScholarshipType.FULL,
      description: "A prestigious scholarship for African students demonstrating academic excellence, leadership potential, and commitment to social justice.",
      eligibility: "Open to African citizens under 30 years with leadership experience and commitment to reconciliation and justice.",
      deadline: new Date("2025-02-28"),
      applicationOpenDate: new Date("2024-10-01"),
      website: "https://mandelarhodes.org",
      fieldOfStudy: ["All Fields"],
      degreeLevel: [DegreeLevel.MASTER],
      minGPA: 3.5,
      maxAge: 30,
      forAfrican: true,
      targetCountries: [], // All African countries
      requiresIELTS: true,
      minIELTS: 7.0,
      numberOfAwards: 30,
      coversTuition: true,
      coversLiving: true,
      featured: true,
      verified: true,
    },
    {
      name: "DAAD Development-Related Postgraduate Courses",
      provider: "DAAD (German Academic Exchange Service)",
      country: "Germany",
      amount: 40000,
      currency: "EUR",
      type: ScholarshipType.FULL,
      description: "Scholarships for development-related postgraduate courses in Germany for students from developing countries.",
      eligibility: "Applicants from developing countries with at least two years of professional experience.",
      deadline: new Date("2025-04-30"),
      website: "https://www.daad.de/en/",
      fieldOfStudy: ["Engineering", "Agriculture", "Economics", "Health", "Environmental Studies"],
      degreeLevel: [DegreeLevel.MASTER],
      minGPA: 3.0,
      forAfrican: true,
      targetCountries: ["Kenya", "Tanzania", "Uganda", "Nigeria", "Ghana", "Ethiopia"],
      requiresIELTS: true,
      minIELTS: 6.5,
      requiresTOEFL: true,
      minTOEFL: 88,
      numberOfAwards: 150,
      coversTuition: true,
      coversLiving: true,
      coversTravel: true,
      featured: true,
      verified: true,
    },
    {
      name: "Chevening Scholarships",
      provider: "UK Government",
      country: "United Kingdom",
      amount: 45000,
      currency: "GBP",
      type: ScholarshipType.FULL,
      description: "The UK government's global scholarship programme offering awards for one-year Master's degrees.",
      eligibility: "Must have at least 2 years of work experience and meet English language requirements.",
      deadline: new Date("2025-11-02"),
      applicationOpenDate: new Date("2025-08-01"),
      website: "https://www.chevening.org",
      fieldOfStudy: ["All Fields"],
      degreeLevel: [DegreeLevel.MASTER],
      minGPA: 3.3,
      forAfrican: true,
      targetCountries: ["Kenya", "Nigeria", "Ghana", "South Africa", "Zimbabwe"],
      requiresIELTS: true,
      minIELTS: 6.5,
      numberOfAwards: 200,
      coversTuition: true,
      coversLiving: true,
      coversTravel: true,
      featured: true,
      verified: true,
    },
    {
      name: "Aga Khan Foundation International Scholarship",
      provider: "Aga Khan Foundation",
      country: "Multiple Countries",
      amount: 25000,
      currency: "USD",
      type: ScholarshipType.PARTIAL,
      description: "Scholarships for postgraduate studies for outstanding students from developing countries with no other means of financing their studies.",
      eligibility: "Must have no other means of financing studies and demonstrate academic excellence.",
      deadline: new Date("2025-03-31"),
      website: "https://www.akdn.org/akf-scholarships",
      fieldOfStudy: ["All Fields"],
      degreeLevel: [DegreeLevel.MASTER, DegreeLevel.PHD],
      minGPA: 3.5,
      forAfrican: true,
      targetCountries: ["Kenya", "Tanzania", "Uganda", "Mozambique", "Madagascar"],
      requiresIELTS: true,
      minIELTS: 6.5,
      numberOfAwards: 50,
      coversTuition: true,
      coversLiving: false,
      verified: true,
    },
    {
      name: "African Graduate Fellowship Program",
      provider: "International Development Research Centre",
      country: "Canada",
      amount: 35000,
      currency: "CAD",
      type: ScholarshipType.FULL,
      description: "Supports African graduate students pursuing research-focused Master's or PhD studies.",
      eligibility: "African nationals enrolled in African universities.",
      deadline: new Date("2025-06-15"),
      website: "https://www.idrc.ca/en/funding",
      fieldOfStudy: ["Research", "Development Studies", "Agriculture", "Health"],
      degreeLevel: [DegreeLevel.MASTER, DegreeLevel.PHD],
      minGPA: 3.3,
      forAfrican: true,
      requiresIELTS: true,
      minIELTS: 6.0,
      numberOfAwards: 40,
      coversTuition: true,
      coversLiving: true,
      verified: true,
    },
    {
      name: "MasterCard Foundation Scholars at University of Cape Town",
      provider: "MasterCard Foundation & UCT",
      country: "South Africa",
      amount: 60000,
      currency: "USD",
      type: ScholarshipType.FULL,
      description: "Comprehensive scholarship for academically talented students from economically disadvantaged backgrounds.",
      eligibility: "African students with strong academic records and leadership potential.",
      deadline: new Date("2025-08-31"),
      website: "https://www.uct.ac.za/mastercard",
      fieldOfStudy: ["All Fields"],
      degreeLevel: [DegreeLevel.BACHELOR, DegreeLevel.MASTER],
      minGPA: 3.2,
      maxAge: 29,
      forAfrican: true,
      targetCountries: ["South Africa", "Zimbabwe", "Lesotho", "Botswana"],
      requiresIELTS: true,
      minIELTS: 6.0,
      numberOfAwards: 60,
      renewableYears: 4,
      coversTuition: true,
      coversLiving: true,
      coversTravel: true,
      coversBooks: true,
      featured: true,
      verified: true,
    },
    {
      name: "Google Women Techmakers Scholars Program",
      provider: "Google",
      country: "Global",
      amount: 10000,
      currency: "USD",
      type: ScholarshipType.PARTIAL,
      description: "Supporting women in technology through financial assistance and mentorship.",
      eligibility: "Female students studying computer science or related technical fields.",
      deadline: new Date("2025-12-31"),
      website: "https://www.womentechmakers.com",
      fieldOfStudy: ["Computer Science", "Engineering", "Technology"],
      degreeLevel: [DegreeLevel.BACHELOR, DegreeLevel.MASTER, DegreeLevel.PHD],
      minGPA: 3.0,
      forWomen: true,
      requiresIELTS: false,
      numberOfAwards: 100,
      coversTuition: true,
      featured: true,
      verified: true,
    },
    {
      name: "African Leadership Academy Scholarships",
      provider: "African Leadership Academy",
      country: "South Africa",
      amount: 75000,
      currency: "USD",
      type: ScholarshipType.FULL,
      description: "Pre-university program preparing the next generation of African leaders.",
      eligibility: "African students aged 15-19 with leadership potential.",
      deadline: new Date("2025-02-15"),
      website: "https://www.africanleadershipacademy.org",
      fieldOfStudy: ["Leadership", "All Fields"],
      degreeLevel: [DegreeLevel.DIPLOMA],
      minGPA: 3.0,
      maxAge: 19,
      minAge: 15,
      forAfrican: true,
      numberOfAwards: 100,
      renewableYears: 2,
      coversTuition: true,
      coversLiving: true,
      coversBooks: true,
      featured: true,
      verified: true,
    },
  ]

  for (const scholarship of scholarships) {
    await prisma.scholarship.create({
      data: scholarship
    })
    console.log(`✅ Created: ${scholarship.name}`)
  }

  console.log('🎉 Seeding completed!')
}

main()
  .catch((e) => {
    console.error('❌ Seeding failed:', e)
    process.exit(1)
  })
  .finally(async () => {
    await prisma.$disconnect()
  })
