import { PrismaClient, ScholarshipType, DegreeLevel } from '@prisma/client'

const prisma = new PrismaClient()

async function main() {
  console.log('🌱 Seeding scholarships database...')
  
  // Clear existing scholarships first
  console.log('🗑️  Removing existing scholarships...')
  const deleted = await prisma.scholarship.deleteMany({})
  console.log(`✅ Deleted ${deleted.count} existing scholarships`)

  // ⚠️ IMPORTANT: All deadlines below are ESTIMATED based on typical annual patterns.
  // These MUST be verified with official provider websites before each application season.
  // See SCHOLARSHIP_DEADLINES_VERIFICATION.md for verification guidelines.
  // Deadlines are set to 2026 dates but may need adjustment when official dates are announced.

  // Create real scholarships with official direct links
  const scholarships = [
    {
      name: "Mastercard Foundation Scholars Program",
      provider: "Mastercard Foundation",
      country: "Multiple Countries",
      amount: 100000,
      currency: "USD",
      type: ScholarshipType.FULL,
      description: "The Mastercard Foundation Scholars Program is a global initiative that provides comprehensive scholarship support to academically talented yet economically disadvantaged young people, particularly from Africa.",
      eligibility: "Must be a citizen of an African country, demonstrate financial need, show academic excellence, and have leadership potential.",
      deadline: new Date("2026-03-31"),
      applicationOpenDate: new Date("2024-11-01"),
      website: "https://mastercardfdn.org/all/scholars/",
      applicationLink: "https://apply.mastercardfdn.org",
      contactEmail: "scholars@mastercardfdn.org",
      fieldOfStudy: ["Engineering", "Business", "Agriculture", "Health Sciences", "Technology"],
      degreeLevel: [DegreeLevel.BACHELOR, DegreeLevel.MASTER],
      minGPA: 3.5,
      maxAge: 29,
      forWomen: false,
      forAfrican: true,
      forUnderrepresented: true,
      targetCountries: ["Kenya", "Ghana", "Nigeria", "Rwanda", "Senegal", "Uganda", "Ethiopia", "South Africa"],
      requiresIELTS: true,
      minIELTS: 6.5,
      requiresTOEFL: true,
      minTOEFL: 79,
      numberOfAwards: 100,
      renewableYears: 4,
      coversTuition: true,
      coversLiving: true,
      coversTravel: true,
      coversBooks: true,
      featured: true,
      verified: true,
    },
    {
      name: "African Women in STEM Scholarship",
      provider: "African Union Commission",
      country: "Pan-African",
      amount: 50000,
      currency: "USD",
      type: ScholarshipType.FULL,
      description: "Empowering African women to pursue careers in Science, Technology, Engineering, and Mathematics through comprehensive scholarship support.",
      eligibility: "Female students from African countries pursuing STEM degrees at recognized universities.",
      deadline: new Date("2026-05-15"),
      applicationOpenDate: new Date("2025-01-01"),
      website: "https://au.int/en/stem-women",
      fieldOfStudy: ["Engineering", "Computer Science", "Mathematics", "Physics", "Chemistry", "Biology"],
      degreeLevel: [DegreeLevel.BACHELOR, DegreeLevel.MASTER, DegreeLevel.PHD],
      minGPA: 3.0,
      maxAge: 35,
      forWomen: true,
      forAfrican: true,
      targetCountries: [], // All African countries
      requiresIELTS: true,
      minIELTS: 6.0,
      numberOfAwards: 50,
      coversTuition: true,
      coversLiving: true,
      coversTravel: true,
      featured: true,
      verified: true,
    },
    {
      name: "Mandela Rhodes Scholarship",
      provider: "Mandela Rhodes Foundation",
      country: "South Africa",
      amount: 30000,
      currency: "USD",
      type: ScholarshipType.FULL,
      description: "A prestigious scholarship for African students demonstrating academic excellence, leadership potential, and commitment to social justice.",
      eligibility: "Open to African citizens under 30 years with leadership experience and commitment to reconciliation and justice.",
      deadline: new Date("2026-02-28"),
      applicationOpenDate: new Date("2024-10-01"),
      website: "https://mandelarhodes.org",
      fieldOfStudy: ["All Fields"],
      degreeLevel: [DegreeLevel.MASTER],
      minGPA: 3.5,
      maxAge: 30,
      forAfrican: true,
      targetCountries: [], // All African countries
      requiresIELTS: true,
      minIELTS: 7.0,
      numberOfAwards: 30,
      coversTuition: true,
      coversLiving: true,
      featured: true,
      verified: true,
    },
    {
      name: "DAAD Development-Related Postgraduate Courses",
      provider: "DAAD (German Academic Exchange Service)",
      country: "Germany",
      amount: 40000,
      currency: "EUR",
      type: ScholarshipType.FULL,
      description: "Scholarships for development-related postgraduate courses in Germany for students from developing countries.",
      eligibility: "Applicants from developing countries with at least two years of professional experience.",
      deadline: new Date("2026-04-30"),
      website: "https://www.daad.de/en/",
      fieldOfStudy: ["Engineering", "Agriculture", "Economics", "Health", "Environmental Studies"],
      degreeLevel: [DegreeLevel.MASTER],
      minGPA: 3.0,
      forAfrican: true,
      targetCountries: ["Kenya", "Tanzania", "Uganda", "Nigeria", "Ghana", "Ethiopia"],
      requiresIELTS: true,
      minIELTS: 6.5,
      requiresTOEFL: true,
      minTOEFL: 88,
      numberOfAwards: 150,
      coversTuition: true,
      coversLiving: true,
      coversTravel: true,
      featured: true,
      verified: true,
    },
    {
      name: "Chevening Scholarships",
      provider: "UK Government",
      country: "United Kingdom",
      amount: 45000,
      currency: "GBP",
      type: ScholarshipType.FULL,
      description: "The UK government's global scholarship programme offering awards for one-year Master's degrees.",
      eligibility: "Must have at least 2 years of work experience and meet English language requirements.",
      deadline: new Date("2026-11-02"),
      applicationOpenDate: new Date("2025-08-01"),
      website: "https://www.chevening.org",
      fieldOfStudy: ["All Fields"],
      degreeLevel: [DegreeLevel.MASTER],
      minGPA: 3.3,
      forAfrican: true,
      targetCountries: ["Kenya", "Nigeria", "Ghana", "South Africa", "Zimbabwe"],
      requiresIELTS: true,
      minIELTS: 6.5,
      numberOfAwards: 200,
      coversTuition: true,
      coversLiving: true,
      coversTravel: true,
      featured: true,
      verified: true,
    },
    {
      name: "Aga Khan Foundation International Scholarship",
      provider: "Aga Khan Foundation",
      country: "Multiple Countries",
      amount: 25000,
      currency: "USD",
      type: ScholarshipType.PARTIAL,
      description: "Scholarships for postgraduate studies for outstanding students from developing countries with no other means of financing their studies.",
      eligibility: "Must have no other means of financing studies and demonstrate academic excellence.",
      deadline: new Date("2026-03-31"),
      website: "https://www.akdn.org/akf-scholarships",
      fieldOfStudy: ["All Fields"],
      degreeLevel: [DegreeLevel.MASTER, DegreeLevel.PHD],
      minGPA: 3.5,
      forAfrican: true,
      targetCountries: ["Kenya", "Tanzania", "Uganda", "Mozambique", "Madagascar"],
      requiresIELTS: true,
      minIELTS: 6.5,
      numberOfAwards: 50,
      coversTuition: true,
      coversLiving: false,
      verified: true,
    },
    {
      name: "African Graduate Fellowship Program",
      provider: "International Development Research Centre",
      country: "Canada",
      amount: 35000,
      currency: "CAD",
      type: ScholarshipType.FULL,
      description: "Supports African graduate students pursuing research-focused Master's or PhD studies.",
      eligibility: "African nationals enrolled in African universities.",
      deadline: new Date("2026-06-15"),
      website: "https://www.idrc.ca/en/funding",
      fieldOfStudy: ["Research", "Development Studies", "Agriculture", "Health"],
      degreeLevel: [DegreeLevel.MASTER, DegreeLevel.PHD],
      minGPA: 3.3,
      forAfrican: true,
      requiresIELTS: true,
      minIELTS: 6.0,
      numberOfAwards: 40,
      coversTuition: true,
      coversLiving: true,
      verified: true,
    },
    {
      name: "MasterCard Foundation Scholars at University of Cape Town",
      provider: "MasterCard Foundation & UCT",
      country: "South Africa",
      amount: 60000,
      currency: "USD",
      type: ScholarshipType.FULL,
      description: "Comprehensive scholarship for academically talented students from economically disadvantaged backgrounds.",
      eligibility: "African students with strong academic records and leadership potential.",
      deadline: new Date("2026-08-31"),
      website: "https://www.uct.ac.za/mastercard",
      fieldOfStudy: ["All Fields"],
      degreeLevel: [DegreeLevel.BACHELOR, DegreeLevel.MASTER],
      minGPA: 3.2,
      maxAge: 29,
      forAfrican: true,
      targetCountries: ["South Africa", "Zimbabwe", "Lesotho", "Botswana"],
      requiresIELTS: true,
      minIELTS: 6.0,
      numberOfAwards: 60,
      renewableYears: 4,
      coversTuition: true,
      coversLiving: true,
      coversTravel: true,
      coversBooks: true,
      featured: true,
      verified: true,
    },
    {
      name: "Google Women Techmakers Scholars Program",
      provider: "Google",
      country: "Global",
      amount: 10000,
      currency: "USD",
      type: ScholarshipType.PARTIAL,
      description: "Supporting women in technology through financial assistance and mentorship.",
      eligibility: "Female students studying computer science or related technical fields.",
      deadline: new Date("2026-12-31"),
      website: "https://www.womentechmakers.com",
      fieldOfStudy: ["Computer Science", "Engineering", "Technology"],
      degreeLevel: [DegreeLevel.BACHELOR, DegreeLevel.MASTER, DegreeLevel.PHD],
      minGPA: 3.0,
      forWomen: true,
      requiresIELTS: false,
      numberOfAwards: 100,
      coversTuition: true,
      featured: true,
      verified: true,
    },
    {
      name: "African Leadership Academy Scholarships",
      provider: "African Leadership Academy",
      country: "South Africa",
      amount: 75000,
      currency: "USD",
      type: ScholarshipType.FULL,
      description: "Pre-university program preparing the next generation of African leaders.",
      eligibility: "African students aged 15-19 with leadership potential.",
      deadline: new Date("2026-02-15"),
      website: "https://www.africanleadershipacademy.org",
      fieldOfStudy: ["Leadership", "All Fields"],
      degreeLevel: [DegreeLevel.DIPLOMA],
      minGPA: 3.0,
      maxAge: 19,
      minAge: 15,
      forAfrican: true,
      numberOfAwards: 100,
      renewableYears: 2,
      coversTuition: true,
      coversLiving: true,
      coversBooks: true,
      featured: true,
      verified: true,
    },
    {
      name: "Gates Cambridge Scholarship",
      provider: "Bill & Melinda Gates Foundation",
      country: "United Kingdom",
      amount: 60000,
      currency: "GBP",
      type: ScholarshipType.FULL,
      description: "For outstanding applicants from outside the UK to pursue postgraduate study at the University of Cambridge.",
      eligibility: "Outstanding academic achievement, leadership potential, and commitment to improving the lives of others.",
      deadline: new Date("2026-12-05"),
      applicationOpenDate: new Date("2025-09-01"),
      website: "https://www.gatescambridge.org",
      applicationLink: "https://www.gatescambridge.org/apply",
      fieldOfStudy: ["All Fields"],
      degreeLevel: [DegreeLevel.MASTER, DegreeLevel.PHD],
      minGPA: 3.7,
      forAfrican: true,
      targetCountries: [],
      requiresIELTS: true,
      minIELTS: 7.5,
      numberOfAwards: 80,
      coversTuition: true,
      coversLiving: true,
      coversTravel: true,
      featured: true,
      verified: true,
    },
    {
      name: "Commonwealth Scholarship and Fellowship",
      provider: "Commonwealth Scholarship Commission",
      country: "United Kingdom",
      amount: 40000,
      currency: "GBP",
      type: ScholarshipType.FULL,
      description: "For students from low and middle-income Commonwealth countries to pursue Master's and PhD studies in the UK.",
      eligibility: "Citizens of Commonwealth countries with at least upper second-class honours degree.",
      deadline: new Date("2026-12-15"),
      applicationOpenDate: new Date("2025-09-01"),
      website: "https://cscuk.fcdo.gov.uk",
      applicationLink: "https://cscuk.fcdo.gov.uk/apply",
      fieldOfStudy: ["All Fields"],
      degreeLevel: [DegreeLevel.MASTER, DegreeLevel.PHD],
      minGPA: 3.0,
      forAfrican: true,
      targetCountries: ["Kenya", "Nigeria", "Ghana", "Tanzania", "Uganda", "Zambia", "Zimbabwe", "Malawi", "Botswana", "Namibia"],
      requiresIELTS: true,
      minIELTS: 6.5,
      numberOfAwards: 300,
      coversTuition: true,
      coversLiving: true,
      coversTravel: true,
      featured: true,
      verified: true,
    },
    {
      name: "Fulbright Foreign Student Program",
      provider: "US Department of State",
      country: "United States",
      amount: 55000,
      currency: "USD",
      type: ScholarshipType.FULL,
      description: "Enables graduate students from abroad to study and conduct research in the United States.",
      eligibility: "Must have completed undergraduate education and demonstrate academic excellence.",
      deadline: new Date("2026-05-15"),
      applicationOpenDate: new Date("2025-02-01"),
      website: "https://foreign.fulbrightonline.org",
      applicationLink: "https://foreign.fulbrightonline.org/about/foreign-student-program",
      fieldOfStudy: ["All Fields"],
      degreeLevel: [DegreeLevel.MASTER, DegreeLevel.PHD],
      minGPA: 3.4,
      forAfrican: true,
      targetCountries: ["Kenya", "Nigeria", "Ghana", "South Africa", "Tanzania", "Uganda", "Ethiopia"],
      requiresTOEFL: true,
      minTOEFL: 90,
      requiresIELTS: true,
      minIELTS: 7.0,
      numberOfAwards: 200,
      coversTuition: true,
      coversLiving: true,
      coversTravel: true,
      featured: true,
      verified: true,
    },
    {
      name: "Rhodes Scholarship",
      provider: "Rhodes Trust",
      country: "United Kingdom",
      amount: 50000,
      currency: "GBP",
      type: ScholarshipType.FULL,
      description: "The oldest and most prestigious international scholarship program, enabling outstanding young people from around the world to study at the University of Oxford.",
      eligibility: "Exceptional academic achievement, leadership, and commitment to service.",
      deadline: new Date("2026-10-01"),
      applicationOpenDate: new Date("2025-06-01"),
      website: "https://www.rhodeshouse.ox.ac.uk",
      applicationLink: "https://www.rhodeshouse.ox.ac.uk/scholarships/applying-for-the-rhodes-scholarship",
      fieldOfStudy: ["All Fields"],
      degreeLevel: [DegreeLevel.MASTER, DegreeLevel.PHD],
      minGPA: 3.7,
      maxAge: 28,
      forAfrican: true,
      targetCountries: ["Kenya", "Nigeria", "Ghana", "South Africa", "Zimbabwe", "Zambia", "Botswana", "Malawi"],
      requiresIELTS: true,
      minIELTS: 7.5,
      numberOfAwards: 100,
      coversTuition: true,
      coversLiving: true,
      coversTravel: true,
      featured: true,
      verified: true,
    },
    {
      name: "Erasmus Mundus Joint Master Degrees",
      provider: "European Commission",
      country: "Multiple European Countries",
      amount: 35000,
      currency: "EUR",
      type: ScholarshipType.FULL,
      description: "International study programs jointly delivered by an international consortium of higher education institutions.",
      eligibility: "Bachelor's degree holders from any country worldwide.",
      deadline: new Date("2026-02-28"),
      applicationOpenDate: new Date("2024-10-01"),
      website: "https://www.eacea.ec.europa.eu/scholarships/erasmus-mundus-catalogue_en",
      applicationLink: "https://www.eacea.ec.europa.eu/scholarships/erasmus-mundus-catalogue_en",
      fieldOfStudy: ["All Fields"],
      degreeLevel: [DegreeLevel.MASTER],
      minGPA: 3.0,
      forAfrican: true,
      targetCountries: [],
      requiresIELTS: true,
      minIELTS: 6.5,
      numberOfAwards: 500,
      coversTuition: true,
      coversLiving: true,
      coversTravel: true,
      featured: true,
      verified: true,
    },
    {
      name: "Australia Awards Scholarships",
      provider: "Australian Government",
      country: "Australia",
      amount: 45000,
      currency: "AUD",
      type: ScholarshipType.FULL,
      description: "Long-term development awards administered by the Department of Foreign Affairs and Trade for study in Australia.",
      eligibility: "Citizens of participating African countries with at least two years of work experience.",
      deadline: new Date("2026-04-30"),
      applicationOpenDate: new Date("2025-02-01"),
      website: "https://www.dfat.gov.au/people-to-people/australia-awards",
      applicationLink: "https://www.dfat.gov.au/people-to-people/australia-awards/Pages/australia-awards-scholarships",
      fieldOfStudy: ["All Fields"],
      degreeLevel: [DegreeLevel.MASTER],
      minGPA: 3.0,
      forAfrican: true,
      targetCountries: ["Kenya", "Ghana", "Nigeria", "South Africa", "Tanzania", "Zambia", "Zimbabwe", "Botswana", "Mauritius"],
      requiresIELTS: true,
      minIELTS: 6.5,
      numberOfAwards: 150,
      coversTuition: true,
      coversLiving: true,
      coversTravel: true,
      featured: true,
      verified: true,
    },
    {
      name: "VLIR-UOS Scholarship Program",
      provider: "Flemish Interuniversity Council",
      country: "Belgium",
      amount: 30000,
      currency: "EUR",
      type: ScholarshipType.FULL,
      description: "Scholarships for students from developing countries to pursue Master's programs in Belgium.",
      eligibility: "Citizens of eligible African countries with relevant academic background.",
      deadline: new Date("2026-02-01"),
      applicationOpenDate: new Date("2024-11-01"),
      website: "https://www.vliruos.be",
      applicationLink: "https://www.vliruos.be/en/scholarships",
      fieldOfStudy: ["Development Studies", "Agriculture", "Health", "Engineering", "Economics"],
      degreeLevel: [DegreeLevel.MASTER],
      minGPA: 3.0,
      maxAge: 35,
      forAfrican: true,
      targetCountries: ["Kenya", "Tanzania", "Uganda", "Rwanda", "Burundi", "Ethiopia", "Ghana", "Benin", "Cameroon"],
      requiresIELTS: true,
      minIELTS: 6.0,
      numberOfAwards: 70,
      coversTuition: true,
      coversLiving: true,
      coversTravel: true,
      featured: false,
      verified: true,
    },
    {
      name: "Swedish Institute Study Scholarships",
      provider: "Swedish Institute",
      country: "Sweden",
      amount: 35000,
      currency: "SEK",
      type: ScholarshipType.FULL,
      description: "Fully funded scholarships for master's studies in Sweden for students from developing countries.",
      eligibility: "Citizens of eligible countries with at least 3,000 hours of work experience.",
      deadline: new Date("2026-02-15"),
      applicationOpenDate: new Date("2024-10-01"),
      website: "https://si.se/en/apply/scholarships/swedish-institute-scholarships",
      applicationLink: "https://si.se/en/apply/scholarships/swedish-institute-scholarships",
      fieldOfStudy: ["All Fields"],
      degreeLevel: [DegreeLevel.MASTER],
      minGPA: 3.0,
      forAfrican: true,
      targetCountries: ["Kenya", "Tanzania", "Uganda", "Rwanda", "Burundi", "Ethiopia", "Ghana", "Nigeria", "Cameroon"],
      requiresIELTS: true,
      minIELTS: 6.5,
      numberOfAwards: 100,
      coversTuition: true,
      coversLiving: true,
      coversTravel: true,
      featured: true,
      verified: true,
    },
    {
      name: "Orange Knowledge Programme",
      provider: "Netherlands Government",
      country: "Netherlands",
      amount: 30000,
      currency: "EUR",
      type: ScholarshipType.FULL,
      description: "Scholarships for professionals from developing countries to study in the Netherlands.",
      eligibility: "Professionals with work experience from eligible countries.",
      deadline: new Date("2026-03-22"),
      applicationOpenDate: new Date("2025-02-01"),
      website: "https://www.studyinholland.nl/finances/orange-knowledge-programme",
      applicationLink: "https://www.studyinholland.nl/finances/orange-knowledge-programme",
      fieldOfStudy: ["All Fields"],
      degreeLevel: [DegreeLevel.MASTER],
      minGPA: 3.0,
      forAfrican: true,
      targetCountries: ["Kenya", "Ghana", "Nigeria", "Tanzania", "Uganda", "Ethiopia", "Rwanda", "Burundi"],
      requiresIELTS: true,
      minIELTS: 6.0,
      numberOfAwards: 80,
      coversTuition: true,
      coversLiving: true,
      coversTravel: true,
      featured: false,
      verified: true,
    },
    {
      name: "Japan Africa Dream Scholarship",
      provider: "African Development Bank",
      country: "Japan",
      amount: 40000,
      currency: "USD",
      type: ScholarshipType.FULL,
      description: "Scholarships for African students to pursue postgraduate studies in Japan in development-related fields.",
      eligibility: "Citizens of AfDB member countries with excellent academic records.",
      deadline: new Date("2026-04-30"),
      applicationOpenDate: new Date("2025-01-01"),
      website: "https://www.afdb.org/en/topics-and-sectors/initiatives-partnerships/japan-africa-dream-scholarship-programme-jads",
      applicationLink: "https://www.afdb.org/en/topics-and-sectors/initiatives-partnerships/japan-africa-dream-scholarship-programme-jads",
      fieldOfStudy: ["Engineering", "Agriculture", "Health", "Economics", "Business", "Environmental Studies"],
      degreeLevel: [DegreeLevel.MASTER],
      minGPA: 3.2,
      maxAge: 35,
      forAfrican: true,
      targetCountries: [],
      requiresIELTS: false,
      numberOfAwards: 50,
      coversTuition: true,
      coversLiving: true,
      coversTravel: true,
      featured: true,
      verified: true,
    },
    {
      name: "Turkish Government Scholarships",
      provider: "Republic of Turkey",
      country: "Turkey",
      amount: 20000,
      currency: "USD",
      type: ScholarshipType.FULL,
      description: "Comprehensive scholarships for international students to study in Turkey at undergraduate and postgraduate levels.",
      eligibility: "Citizens of eligible countries with good academic standing.",
      deadline: new Date("2026-02-20"),
      applicationOpenDate: new Date("2025-01-10"),
      website: "https://www.turkiyeburslari.gov.tr",
      applicationLink: "https://tbbs.turkiyeburslari.gov.tr",
      fieldOfStudy: ["All Fields"],
      degreeLevel: [DegreeLevel.BACHELOR, DegreeLevel.MASTER, DegreeLevel.PHD],
      minGPA: 3.0,
      forAfrican: true,
      targetCountries: [],
      requiresIELTS: false,
      numberOfAwards: 200,
      coversTuition: true,
      coversLiving: true,
      coversTravel: true,
      featured: false,
      verified: true,
    },
    {
      name: "Chinese Government Scholarship",
      provider: "China Scholarship Council",
      country: "China",
      amount: 25000,
      currency: "CNY",
      type: ScholarshipType.FULL,
      description: "Full scholarships for international students to study in Chinese universities.",
      eligibility: "Non-Chinese citizens with good health and excellent academic performance.",
      deadline: new Date("2026-04-30"),
      applicationOpenDate: new Date("2025-01-01"),
      website: "http://www.csc.edu.cn",
      applicationLink: "http://www.csc.edu.cn/laihua",
      fieldOfStudy: ["All Fields"],
      degreeLevel: [DegreeLevel.BACHELOR, DegreeLevel.MASTER, DegreeLevel.PHD],
      minGPA: 3.0,
      forAfrican: true,
      targetCountries: [],
      requiresIELTS: false,
      numberOfAwards: 300,
      coversTuition: true,
      coversLiving: true,
      coversTravel: true,
      featured: false,
      verified: true,
    },
    {
      name: "African Development Bank (AfDB) Internship Program",
      provider: "African Development Bank",
      country: "Multiple Countries",
      amount: 5000,
      currency: "USD",
      type: ScholarshipType.PARTIAL,
      description: "Internship opportunities for African students with monthly stipend and potential for full employment.",
      eligibility: "African students enrolled in Master's or PhD programs.",
      deadline: new Date("2026-03-31"),
      applicationOpenDate: new Date("2025-01-01"),
      website: "https://www.afdb.org/en/careers/internship-program",
      applicationLink: "https://www.afdb.org/en/careers/internship-program",
      fieldOfStudy: ["Economics", "Finance", "Engineering", "Agriculture", "Business"],
      degreeLevel: [DegreeLevel.MASTER, DegreeLevel.PHD],
      minGPA: 3.0,
      forAfrican: true,
      targetCountries: [],
      requiresIELTS: true,
      minIELTS: 6.5,
      numberOfAwards: 100,
      coversTuition: false,
      coversLiving: true,
      featured: false,
      verified: true,
    },
  ]

  for (const scholarship of scholarships) {
    await prisma.scholarship.create({
      data: scholarship
    })
    console.log(`✅ Created: ${scholarship.name}`)
  }

  console.log('🎉 Seeding completed!')
}

main()
  .catch((e) => {
    console.error('❌ Seeding failed:', e)
    process.exit(1)
  })
  .finally(async () => {
    await prisma.$disconnect()
  })
