import JSZip from 'jszip';

/**
 * Generate a ZIP file containing copilot documents
 */
export async function generateCopilotZip(documents: any, finderData: any): Promise<Buffer> {
  const zip = new JSZip();
  
  // Add motivation letter
  if (documents.motivationLetter) {
    zip.file('Motivation-Letter.txt', documents.motivationLetter);
    zip.file('Motivation-Letter.md', documents.motivationLetter);
  }
  
  // Add personal statement if different
  if (documents.personalStatement && documents.personalStatement !== documents.motivationLetter) {
    zip.file('Personal-Statement.txt', documents.personalStatement);
  }
  
  // Add form mappings as JSON
  if (documents.filledFormPreview && Array.isArray(documents.filledFormPreview)) {
    zip.file('Form-Mappings.json', JSON.stringify(documents.filledFormPreview, null, 2));
    
    // Create a human-readable form preview
    const formPreview = documents.filledFormPreview
      .map((m: any) => `${m.profileKey || 'Unknown'}: ${m.value || '[Not filled]'}`)
      .join('\n');
    zip.file('Form-Preview.txt', formPreview);
  }
  
  // Add user profile summary
  const profileSummary = `
SCHOLARSHIP APPLICATION PROFILE
================================

Name: ${finderData.name || finderData.paymentName || 'Not provided'}
Email: ${finderData.email || finderData.paymentEmail || 'Not provided'}
Phone: ${finderData.phone || finderData.paymentPhone || 'Not provided'}
Nationality: ${finderData.nationality || 'Not provided'}
Destination: ${finderData.destination || 'Not provided'}
Field of Study: ${finderData.fieldOfStudy || 'Not provided'}
Degree Level: ${finderData.degreeLevel || 'Not provided'}
Funding Type: ${finderData.fundingType || 'Not provided'}
${finderData.currentGPA ? `Current GPA: ${finderData.currentGPA}` : ''}
${finderData.bio ? `\nBackground:\n${finderData.bio}` : ''}

Generated: ${documents.generatedAt || new Date().toISOString()}
  `.trim();
  
  zip.file('Profile-Summary.txt', profileSummary);
  
  // Add README with instructions
  const readme = `
SCHOLARSHIP COPILOT APPLICATION PACKAGE
========================================

This package contains:
1. Motivation-Letter.txt - Your personalized motivation letter
2. Personal-Statement.txt - Your personal statement (if different)
3. Form-Mappings.json - Automated form field mappings
4. Form-Preview.txt - Human-readable form preview
5. Profile-Summary.txt - Your complete profile summary

HOW TO USE:
-----------
1. Review all documents and customize as needed
2. Use the Form-Mappings.json to understand which fields map to your profile
3. Copy your motivation letter into application forms
4. Use the form preview to pre-fill applications
5. Double-check all information before submitting

IMPORTANT NOTES:
---------------
- Always review and personalize documents before submitting
- Some scholarships may require additional documents
- Check each scholarship's specific requirements
- Keep copies of all submitted applications

Need help? Contact us at support@ailesglobal.com

Generated by AILES Global Scholarship Copilot
© ${new Date().getFullYear()} Ailes Global
  `.trim();
  
  zip.file('README.txt', readme);
  
  // Generate ZIP buffer
  const zipBuffer = await zip.generateAsync({
    type: 'nodebuffer',
    compression: 'DEFLATE',
    compressionOptions: { level: 9 }
  });
  
  return zipBuffer;
}

/**
 * Get ZIP file name for a copilot request
 */
export function getZipFileName(copilotRequestId: string, userName?: string): string {
  const sanitizedName = userName 
    ? userName.replace(/[^a-zA-Z0-9]/g, '-').toLowerCase()
    : 'applications';
  const date = new Date().toISOString().split('T')[0];
  return `scholarship-copilot-${sanitizedName}-${date}-${copilotRequestId.slice(0, 8)}.zip`;
}

