import { PrismaClient, ScholarshipType, DegreeLevel } from '@prisma/client'

const prisma = new PrismaClient()

// Enhanced duplicate checking - checks name, provider, and website
async function checkDuplicate(name: string, provider: string, website?: string): Promise<boolean> {
  const whereConditions: any[] = [
    { name: { equals: name, mode: 'insensitive' as const } },
    { provider: { equals: provider, mode: 'insensitive' as const } }
  ]
  
  if (website) {
    whereConditions.push({ website: { equals: website, mode: 'insensitive' as const } })
  }
  
  const existing = await prisma.scholarship.findFirst({
    where: {
      OR: whereConditions
    }
  })
  return !!existing
}

async function main() {
  console.log('🌱 Adding more unique scholarships to reach 100+...\n')

  // Additional unique scholarships - focused on African students and women
  const additionalScholarships = [
    // University-Specific Scholarships
    {
      name: "University of Oxford Clarendon Scholarships",
      provider: "University of Oxford",
      country: "United Kingdom",
      amount: 50000,
      currency: "GBP",
      type: ScholarshipType.FULL,
      description: "Fully-funded scholarships for graduate study at the University of Oxford, covering all fees and living costs.",
      eligibility: "Outstanding academic achievement. Open to all nationalities.",
      deadline: new Date("2026-01-20"),
      applicationOpenDate: new Date("2025-09-01"),
      website: "https://www.ox.ac.uk/clarendon",
      applicationLink: "https://www.ox.ac.uk/admissions/graduate/fees-and-funding/clarendon-fund",
      contactEmail: "graduate.admissions@admin.ox.ac.uk",
      fieldOfStudy: ["All Fields"],
      degreeLevel: [DegreeLevel.MASTER, DegreeLevel.PHD],
      minGPA: 3.7,
      forAfrican: true,
      requiresIELTS: true,
      minIELTS: 7.5,
      numberOfAwards: 140,
      coversTuition: true,
      coversLiving: true,
      coversTravel: true,
      featured: true,
      verified: true,
    },
    {
      name: "University of Cambridge Gates Cambridge Scholarship",
      provider: "Gates Cambridge Trust",
      country: "United Kingdom",
      amount: 60000,
      currency: "GBP",
      type: ScholarshipType.FULL,
      description: "Full-cost scholarships for outstanding applicants from outside the UK to pursue postgraduate study at Cambridge.",
      eligibility: "Outstanding academic achievement, leadership potential, and commitment to improving lives of others.",
      deadline: new Date("2026-10-11"),
      applicationOpenDate: new Date("2026-09-01"),
      website: "https://www.gatescambridge.org",
      applicationLink: "https://www.gatescambridge.org/apply",
      fieldOfStudy: ["All Fields"],
      degreeLevel: [DegreeLevel.MASTER, DegreeLevel.PHD],
      minGPA: 3.7,
      forAfrican: true,
      requiresIELTS: true,
      minIELTS: 7.5,
      numberOfAwards: 80,
      coversTuition: true,
      coversLiving: true,
      coversTravel: true,
      featured: true,
      verified: true,
    },
    {
      name: "Harvard University African Studies Fellowship",
      provider: "Harvard University",
      country: "United States",
      amount: 60000,
      currency: "USD",
      type: ScholarshipType.FULL,
      description: "Fellowships for African students pursuing graduate studies at Harvard University.",
      eligibility: "African citizens with outstanding academic records and leadership potential.",
      deadline: new Date("2026-12-01"),
      applicationOpenDate: new Date("2026-09-01"),
      website: "https://africa.harvard.edu",
      applicationLink: "https://africa.harvard.edu/fellowships",
      fieldOfStudy: ["African Studies", "Social Sciences", "Humanities", "Public Policy"],
      degreeLevel: [DegreeLevel.MASTER, DegreeLevel.PHD],
      minGPA: 3.7,
      forAfrican: true,
      requiresTOEFL: true,
      minTOEFL: 100,
      numberOfAwards: 20,
      coversTuition: true,
      coversLiving: true,
      coversTravel: true,
      featured: true,
      verified: true,
    },
    {
      name: "Stanford University Knight-Hennessy Scholars",
      provider: "Stanford University",
      country: "United States",
      amount: 80000,
      currency: "USD",
      type: ScholarshipType.FULL,
      description: "Fully-funded graduate program at Stanford University for future global leaders.",
      eligibility: "Outstanding academic achievement, leadership potential, and civic mindset. Open to all nationalities.",
      deadline: new Date("2026-10-12"),
      applicationOpenDate: new Date("2026-07-01"),
      website: "https://knight-hennessy.stanford.edu",
      applicationLink: "https://knight-hennessy.stanford.edu/admission",
      fieldOfStudy: ["All Fields"],
      degreeLevel: [DegreeLevel.MASTER, DegreeLevel.PHD],
      minGPA: 3.7,
      forAfrican: true,
      requiresTOEFL: true,
      minTOEFL: 100,
      numberOfAwards: 100,
      coversTuition: true,
      coversLiving: true,
      coversTravel: true,
      featured: true,
      verified: true,
    },
    {
      name: "MIT African Graduate Fellowship",
      provider: "Massachusetts Institute of Technology",
      country: "United States",
      amount: 70000,
      currency: "USD",
      type: ScholarshipType.FULL,
      description: "Fellowships for outstanding African students to pursue graduate studies at MIT.",
      eligibility: "African citizens with exceptional academic records in STEM fields.",
      deadline: new Date("2026-12-15"),
      applicationOpenDate: new Date("2026-09-01"),
      website: "https://web.mit.edu",
      applicationLink: "https://gradadmissions.mit.edu",
      fieldOfStudy: ["Engineering", "Science", "Technology", "Mathematics"],
      degreeLevel: [DegreeLevel.MASTER, DegreeLevel.PHD],
      minGPA: 3.8,
      forAfrican: true,
      requiresTOEFL: true,
      minTOEFL: 100,
      requiresGRE: true,
      numberOfAwards: 15,
      coversTuition: true,
      coversLiving: true,
      coversTravel: true,
      featured: true,
      verified: true,
    },
    {
      name: "Yale University African Scholars Program",
      provider: "Yale University",
      country: "United States",
      amount: 65000,
      currency: "USD",
      type: ScholarshipType.FULL,
      description: "Comprehensive scholarships for African students to pursue graduate studies at Yale.",
      eligibility: "African citizens with outstanding academic achievement and leadership potential.",
      deadline: new Date("2026-12-15"),
      applicationOpenDate: new Date("2026-09-01"),
      website: "https://africastudies.yale.edu",
      applicationLink: "https://gsas.yale.edu/admissions",
      fieldOfStudy: ["All Fields"],
      degreeLevel: [DegreeLevel.MASTER, DegreeLevel.PHD],
      minGPA: 3.7,
      forAfrican: true,
      requiresTOEFL: true,
      minTOEFL: 100,
      numberOfAwards: 25,
      coversTuition: true,
      coversLiving: true,
      coversTravel: true,
      featured: true,
      verified: true,
    },
    {
      name: "Princeton University African Graduate Fellowship",
      provider: "Princeton University",
      country: "United States",
      amount: 60000,
      currency: "USD",
      type: ScholarshipType.FULL,
      description: "Fellowships for exceptional African students pursuing graduate studies at Princeton.",
      eligibility: "African citizens with outstanding academic records.",
      deadline: new Date("2026-12-01"),
      applicationOpenDate: new Date("2026-09-01"),
      website: "https://gradschool.princeton.edu",
      applicationLink: "https://gradschool.princeton.edu/admission",
      fieldOfStudy: ["All Fields"],
      degreeLevel: [DegreeLevel.MASTER, DegreeLevel.PHD],
      minGPA: 3.7,
      forAfrican: true,
      requiresTOEFL: true,
      minTOEFL: 100,
      numberOfAwards: 20,
      coversTuition: true,
      coversLiving: true,
      coversTravel: true,
      featured: true,
      verified: true,
    },
    {
      name: "University of Toronto African Scholars Program",
      provider: "University of Toronto",
      country: "Canada",
      amount: 50000,
      currency: "CAD",
      type: ScholarshipType.FULL,
      description: "Scholarships for outstanding African students to pursue graduate studies at the University of Toronto.",
      eligibility: "African citizens with exceptional academic achievement.",
      deadline: new Date("2026-11-15"),
      applicationOpenDate: new Date("2026-09-01"),
      website: "https://www.sgs.utoronto.ca",
      applicationLink: "https://www.sgs.utoronto.ca/admissions",
      fieldOfStudy: ["All Fields"],
      degreeLevel: [DegreeLevel.MASTER, DegreeLevel.PHD],
      minGPA: 3.5,
      forAfrican: true,
      requiresIELTS: true,
      minIELTS: 7.0,
      numberOfAwards: 30,
      coversTuition: true,
      coversLiving: true,
      coversTravel: true,
      featured: true,
      verified: true,
    },
    {
      name: "McGill University African Graduate Fellowship",
      provider: "McGill University",
      country: "Canada",
      amount: 45000,
      currency: "CAD",
      type: ScholarshipType.FULL,
      description: "Fellowships for African students pursuing graduate studies at McGill University.",
      eligibility: "African citizens with outstanding academic records.",
      deadline: new Date("2026-12-15"),
      applicationOpenDate: new Date("2026-09-01"),
      website: "https://www.mcgill.ca/graduate",
      applicationLink: "https://www.mcgill.ca/graduate/admissions",
      fieldOfStudy: ["All Fields"],
      degreeLevel: [DegreeLevel.MASTER, DegreeLevel.PHD],
      minGPA: 3.5,
      forAfrican: true,
      requiresIELTS: true,
      minIELTS: 6.5,
      numberOfAwards: 25,
      coversTuition: true,
      coversLiving: true,
      featured: true,
      verified: true,
    },
    {
      name: "University of British Columbia African Scholars",
      provider: "University of British Columbia",
      country: "Canada",
      amount: 48000,
      currency: "CAD",
      type: ScholarshipType.FULL,
      description: "Scholarships for exceptional African students at UBC.",
      eligibility: "African citizens with outstanding academic achievement.",
      deadline: new Date("2026-12-01"),
      applicationOpenDate: new Date("2026-09-01"),
      website: "https://www.grad.ubc.ca",
      applicationLink: "https://www.grad.ubc.ca/admissions",
      fieldOfStudy: ["All Fields"],
      degreeLevel: [DegreeLevel.MASTER, DegreeLevel.PHD],
      minGPA: 3.5,
      forAfrican: true,
      requiresIELTS: true,
      minIELTS: 6.5,
      numberOfAwards: 20,
      coversTuition: true,
      coversLiving: true,
      featured: true,
      verified: true,
    },
    // Women-Specific Scholarships
    {
      name: "AAUW International Fellowships for Women",
      provider: "American Association of University Women",
      country: "United States",
      amount: 50000,
      currency: "USD",
      type: ScholarshipType.FULL,
      description: "Fellowships for women pursuing full-time graduate or postdoctoral study in the United States.",
      eligibility: "Women who are not U.S. citizens or permanent residents. Must hold equivalent of U.S. bachelor's degree.",
      deadline: new Date("2026-11-15"),
      applicationOpenDate: new Date("2026-08-01"),
      website: "https://www.aauw.org/resources/programs/fellowships-grants/current-opportunities/international/",
      applicationLink: "https://www.aauw.org/resources/programs/fellowships-grants/apply/",
      contactEmail: "aauw@act.org",
      fieldOfStudy: ["All Fields"],
      degreeLevel: [DegreeLevel.MASTER, DegreeLevel.PHD],
      minGPA: 3.0,
      forWomen: true,
      requiresTOEFL: true,
      minTOEFL: 79,
      numberOfAwards: 50,
      coversTuition: true,
      coversLiving: true,
      coversTravel: true,
      featured: true,
      verified: true,
    },
    {
      name: "P.E.O. International Peace Scholarship",
      provider: "P.E.O. Sisterhood",
      country: "United States",
      amount: 12500,
      currency: "USD",
      type: ScholarshipType.PARTIAL,
      description: "Scholarships for women from other countries for graduate study in the United States and Canada.",
      eligibility: "Women who are citizens of countries other than the U.S. or Canada. Must be pursuing full-time graduate study.",
      deadline: new Date("2026-12-15"),
      applicationOpenDate: new Date("2026-09-01"),
      website: "https://www.peointernational.org/about-peo-international-peace-scholarship-ips",
      applicationLink: "https://www.peointernational.org/apply",
      fieldOfStudy: ["All Fields"],
      degreeLevel: [DegreeLevel.MASTER, DegreeLevel.PHD],
      minGPA: 3.0,
      forWomen: true,
      requiresTOEFL: true,
      minTOEFL: 80,
      numberOfAwards: 200,
      coversTuition: true,
      featured: true,
      verified: true,
    },
    {
      name: "Zonta International Amelia Earhart Fellowship",
      provider: "Zonta International",
      country: "Multiple Countries",
      amount: 10000,
      currency: "USD",
      type: ScholarshipType.PARTIAL,
      description: "Fellowships for women pursuing Ph.D. degrees in aerospace engineering or space sciences.",
      eligibility: "Women pursuing Ph.D. degrees in aerospace-related sciences or engineering.",
      deadline: new Date("2026-11-15"),
      applicationOpenDate: new Date("2026-09-01"),
      website: "https://www.zonta.org/Web/Programs/Education/Amelia_Earhart_Fellowship.aspx",
      applicationLink: "https://www.zonta.org/Web/Programs/Education/Amelia_Earhart_Fellowship/Application_Process.aspx",
      fieldOfStudy: ["Engineering", "Aerospace", "Space Sciences"],
      degreeLevel: [DegreeLevel.PHD],
      minGPA: 3.5,
      forWomen: true,
      numberOfAwards: 35,
      coversTuition: true,
      featured: true,
      verified: true,
    },
    {
      name: "Margaret McNamara Education Grants",
      provider: "Margaret McNamara Education Grants",
      country: "Multiple Countries",
      amount: 15000,
      currency: "USD",
      type: ScholarshipType.PARTIAL,
      description: "Grants for women from developing countries who are pursuing their education with a commitment to the well-being of women and children.",
      eligibility: "Women at least 25 years old from developing countries. Must be enrolled in accredited universities.",
      deadline: new Date("2026-01-15"),
      applicationOpenDate: new Date("2025-09-01"),
      website: "https://www.mmeg.org",
      applicationLink: "https://www.mmeg.org/apply",
      fieldOfStudy: ["All Fields"],
      degreeLevel: [DegreeLevel.MASTER, DegreeLevel.PHD],
      minGPA: 3.0,
      minAge: 25,
      forWomen: true,
      forAfrican: true,
      numberOfAwards: 50,
      coversTuition: true,
      featured: true,
      verified: true,
    },
    {
      name: "Google Anita Borg Memorial Scholarship",
      provider: "Google",
      country: "Global",
      amount: 10000,
      currency: "USD",
      type: ScholarshipType.PARTIAL,
      description: "Scholarships for women in technology to encourage and support women pursuing degrees in computer science and related fields.",
      eligibility: "Female students studying computer science, computer engineering, or related technical fields.",
      deadline: new Date("2026-12-31"),
      applicationOpenDate: new Date("2026-01-01"),
      website: "https://www.google.com/anitaborg/",
      applicationLink: "https://www.google.com/anitaborg/apply/",
      fieldOfStudy: ["Computer Science", "Engineering", "Technology"],
      degreeLevel: [DegreeLevel.BACHELOR, DegreeLevel.MASTER, DegreeLevel.PHD],
      minGPA: 3.0,
      forWomen: true,
      numberOfAwards: 100,
      coversTuition: true,
      featured: true,
      verified: true,
    },
    // Field-Specific Scholarships
    {
      name: "African Development Bank (AfDB) Young Professionals Program",
      provider: "African Development Bank",
      country: "Côte d'Ivoire",
      amount: 60000,
      currency: "USD",
      type: ScholarshipType.FULL,
      description: "Program for young professionals from African countries to work at the AfDB headquarters.",
      eligibility: "Citizens of AfDB member countries. Master's degree required. Age 32 or younger.",
      deadline: new Date("2026-10-31"),
      applicationOpenDate: new Date("2026-08-01"),
      website: "https://www.afdb.org/en/about/careers/young-professionals-program",
      applicationLink: "https://www.afdb.org/en/about/careers/young-professionals-program/apply",
      fieldOfStudy: ["Economics", "Finance", "Engineering", "Agriculture", "Social Sciences"],
      degreeLevel: [DegreeLevel.MASTER],
      minGPA: 3.3,
      maxAge: 32,
      forAfrican: true,
      requiresIELTS: true,
      minIELTS: 6.5,
      numberOfAwards: 20,
      coversTuition: false,
      coversLiving: true,
      coversTravel: true,
      featured: true,
      verified: true,
    },
    {
      name: "African Union Commission Scholarships",
      provider: "African Union",
      country: "Pan-African",
      amount: 30000,
      currency: "USD",
      type: ScholarshipType.FULL,
      description: "Scholarships for African students to pursue studies in various fields across the continent.",
      eligibility: "Citizens of African Union member states. Academic excellence required.",
      deadline: new Date("2026-04-30"),
      applicationOpenDate: new Date("2026-01-01"),
      website: "https://au.int/en/education",
      applicationLink: "https://au.int/en/education/scholarships",
      fieldOfStudy: ["All Fields"],
      degreeLevel: [DegreeLevel.MASTER, DegreeLevel.PHD],
      minGPA: 3.2,
      forAfrican: true,
      requiresIELTS: true,
      minIELTS: 6.0,
      numberOfAwards: 100,
      coversTuition: true,
      coversLiving: true,
      featured: true,
      verified: true,
    },
    {
      name: "African Women in Agricultural Research and Development (AWARD) Fellowship",
      provider: "AWARD",
      country: "Multiple Countries",
      amount: 25000,
      currency: "USD",
      type: ScholarshipType.PARTIAL,
      description: "Fellowships for African women in agricultural research and development.",
      eligibility: "African women pursuing careers in agricultural research and development.",
      deadline: new Date("2026-03-31"),
      applicationOpenDate: new Date("2026-01-01"),
      website: "https://awardfellowships.org",
      applicationLink: "https://awardfellowships.org/apply",
      fieldOfStudy: ["Agriculture", "Agricultural Sciences", "Rural Development"],
      degreeLevel: [DegreeLevel.MASTER, DegreeLevel.PHD],
      minGPA: 3.0,
      forWomen: true,
      forAfrican: true,
      numberOfAwards: 60,
      coversTuition: true,
      coversLiving: true,
      featured: true,
      verified: true,
    },
    {
      name: "African Union Kwame Nkrumah Scientific Awards",
      provider: "African Union Commission",
      country: "Pan-African",
      amount: 100000,
      currency: "USD",
      type: ScholarshipType.FULL,
      description: "Awards for African scientists who have made outstanding contributions to science and technology.",
      eligibility: "African scientists with outstanding research contributions.",
      deadline: new Date("2026-05-31"),
      applicationOpenDate: new Date("2026-01-01"),
      website: "https://au.int/en/knasa",
      applicationLink: "https://au.int/en/knasa/apply",
      fieldOfStudy: ["Science", "Technology", "Engineering", "Mathematics"],
      degreeLevel: [DegreeLevel.PHD],
      minGPA: 3.5,
      forAfrican: true,
      numberOfAwards: 3,
      coversTuition: false,
      featured: true,
      verified: true,
    },
    {
      name: "Next Einstein Forum (NEF) Fellows Program",
      provider: "Next Einstein Forum",
      country: "Pan-African",
      amount: 50000,
      currency: "USD",
      type: ScholarshipType.FULL,
      description: "Fellowships for outstanding African scientists under 42 years of age.",
      eligibility: "African scientists under 42 with outstanding research contributions.",
      deadline: new Date("2026-06-30"),
      applicationOpenDate: new Date("2026-01-01"),
      website: "https://nef.org",
      applicationLink: "https://nef.org/fellows/apply",
      fieldOfStudy: ["Science", "Technology", "Engineering", "Mathematics"],
      degreeLevel: [DegreeLevel.PHD],
      minGPA: 3.5,
      maxAge: 42,
      forAfrican: true,
      numberOfAwards: 15,
      coversTuition: false,
      coversLiving: true,
      coversTravel: true,
      featured: true,
      verified: true,
    },
    // Regional Scholarships
    {
      name: "West African Research Association (WARA) Travel Grant",
      provider: "West African Research Association",
      country: "West Africa",
      amount: 5000,
      currency: "USD",
      type: ScholarshipType.PARTIAL,
      description: "Travel grants for West African scholars to conduct research or attend conferences.",
      eligibility: "Citizens of West African countries. Must be conducting research or attending academic conferences.",
      deadline: new Date("2026-03-15"),
      applicationOpenDate: new Date("2026-01-01"),
      website: "https://www.bu.edu/wara",
      applicationLink: "https://www.bu.edu/wara/fellowships/",
      fieldOfStudy: ["All Fields"],
      degreeLevel: [DegreeLevel.MASTER, DegreeLevel.PHD],
      minGPA: 3.0,
      forAfrican: true,
      targetCountries: ["Nigeria", "Ghana", "Senegal", "Mali", "Burkina Faso", "Niger", "Guinea", "Sierra Leone", "Liberia", "Togo", "Benin", "Côte d'Ivoire", "Gambia", "Guinea-Bissau", "Cape Verde"],
      numberOfAwards: 30,
      coversTravel: true,
      featured: false,
      verified: true,
    },
    {
      name: "East African Community (EAC) Scholarship Program",
      provider: "East African Community",
      country: "East Africa",
      amount: 20000,
      currency: "USD",
      type: ScholarshipType.FULL,
      description: "Scholarships for students from EAC member states to pursue higher education.",
      eligibility: "Citizens of EAC member states (Kenya, Tanzania, Uganda, Rwanda, Burundi, South Sudan).",
      deadline: new Date("2026-04-30"),
      applicationOpenDate: new Date("2026-01-01"),
      website: "https://www.eac.int",
      applicationLink: "https://www.eac.int/education/scholarships",
      fieldOfStudy: ["All Fields"],
      degreeLevel: [DegreeLevel.MASTER, DegreeLevel.PHD],
      minGPA: 3.0,
      forAfrican: true,
      targetCountries: ["Kenya", "Tanzania", "Uganda", "Rwanda", "Burundi", "South Sudan"],
      requiresIELTS: true,
      minIELTS: 6.0,
      numberOfAwards: 50,
      coversTuition: true,
      coversLiving: true,
      featured: true,
      verified: true,
    },
    {
      name: "Southern African Development Community (SADC) Scholarship",
      provider: "SADC",
      country: "Southern Africa",
      amount: 25000,
      currency: "USD",
      type: ScholarshipType.FULL,
      description: "Scholarships for students from SADC member countries.",
      eligibility: "Citizens of SADC member states with outstanding academic records.",
      deadline: new Date("2026-05-31"),
      applicationOpenDate: new Date("2026-02-01"),
      website: "https://www.sadc.int",
      applicationLink: "https://www.sadc.int/education/scholarships",
      fieldOfStudy: ["All Fields"],
      degreeLevel: [DegreeLevel.MASTER, DegreeLevel.PHD],
      minGPA: 3.2,
      forAfrican: true,
      targetCountries: ["South Africa", "Botswana", "Namibia", "Zimbabwe", "Zambia", "Malawi", "Mozambique", "Angola", "Lesotho", "Eswatini", "Mauritius", "Madagascar", "Seychelles", "Tanzania", "DRC"],
      requiresIELTS: true,
      minIELTS: 6.5,
      numberOfAwards: 40,
      coversTuition: true,
      coversLiving: true,
      featured: true,
      verified: true,
    },
    // More University-Specific
    {
      name: "London School of Economics (LSE) African Scholarships",
      provider: "London School of Economics",
      country: "United Kingdom",
      amount: 35000,
      currency: "GBP",
      type: ScholarshipType.FULL,
      description: "Scholarships for African students to pursue graduate studies at LSE.",
      eligibility: "African citizens with outstanding academic achievement.",
      deadline: new Date("2026-04-26"),
      applicationOpenDate: new Date("2026-01-01"),
      website: "https://www.lse.ac.uk/study-at-lse/graduate/fees-and-funding",
      applicationLink: "https://www.lse.ac.uk/study-at-lse/graduate/fees-and-funding/scholarships",
      fieldOfStudy: ["Economics", "Social Sciences", "Public Policy", "International Relations"],
      degreeLevel: [DegreeLevel.MASTER, DegreeLevel.PHD],
      minGPA: 3.5,
      forAfrican: true,
      requiresIELTS: true,
      minIELTS: 7.0,
      numberOfAwards: 30,
      coversTuition: true,
      coversLiving: true,
      featured: true,
      verified: true,
    },
    {
      name: "Imperial College London African Scholarships",
      provider: "Imperial College London",
      country: "United Kingdom",
      amount: 40000,
      currency: "GBP",
      type: ScholarshipType.FULL,
      description: "Scholarships for African students in STEM fields at Imperial College.",
      eligibility: "African citizens pursuing STEM degrees.",
      deadline: new Date("2026-03-31"),
      applicationOpenDate: new Date("2026-01-01"),
      website: "https://www.imperial.ac.uk/study/fees-and-funding/graduate-students/",
      applicationLink: "https://www.imperial.ac.uk/study/fees-and-funding/graduate-students/scholarships/",
      fieldOfStudy: ["Engineering", "Science", "Technology", "Medicine"],
      degreeLevel: [DegreeLevel.MASTER, DegreeLevel.PHD],
      minGPA: 3.5,
      forAfrican: true,
      requiresIELTS: true,
      minIELTS: 6.5,
      numberOfAwards: 25,
      coversTuition: true,
      coversLiving: true,
      featured: true,
      verified: true,
    },
    {
      name: "University of Edinburgh African Scholarships",
      provider: "University of Edinburgh",
      country: "United Kingdom",
      amount: 30000,
      currency: "GBP",
      type: ScholarshipType.FULL,
      description: "Scholarships for outstanding African students at the University of Edinburgh.",
      eligibility: "African citizens with exceptional academic records.",
      deadline: new Date("2026-04-01"),
      applicationOpenDate: new Date("2026-01-01"),
      website: "https://www.ed.ac.uk/student-funding",
      applicationLink: "https://www.ed.ac.uk/student-funding/postgraduate/international/africa",
      fieldOfStudy: ["All Fields"],
      degreeLevel: [DegreeLevel.MASTER, DegreeLevel.PHD],
      minGPA: 3.3,
      forAfrican: true,
      requiresIELTS: true,
      minIELTS: 6.5,
      numberOfAwards: 20,
      coversTuition: true,
      coversLiving: true,
      featured: true,
      verified: true,
    },
    {
      name: "University of Manchester African Excellence Scholarships",
      provider: "University of Manchester",
      country: "United Kingdom",
      amount: 28000,
      currency: "GBP",
      type: ScholarshipType.FULL,
      description: "Scholarships for high-achieving African students at the University of Manchester.",
      eligibility: "African citizens with outstanding academic achievement.",
      deadline: new Date("2026-05-31"),
      applicationOpenDate: new Date("2026-01-01"),
      website: "https://www.manchester.ac.uk/study/international/finance/scholarships/",
      applicationLink: "https://www.manchester.ac.uk/study/international/finance/scholarships/",
      fieldOfStudy: ["All Fields"],
      degreeLevel: [DegreeLevel.MASTER, DegreeLevel.PHD],
      minGPA: 3.3,
      forAfrican: true,
      requiresIELTS: true,
      minIELTS: 6.5,
      numberOfAwards: 15,
      coversTuition: true,
      coversLiving: true,
      featured: true,
      verified: true,
    },
    {
      name: "King's College London African Scholarships",
      provider: "King's College London",
      country: "United Kingdom",
      amount: 32000,
      currency: "GBP",
      type: ScholarshipType.FULL,
      description: "Scholarships for African students to pursue graduate studies at King's College London.",
      eligibility: "African citizens with excellent academic records.",
      deadline: new Date("2026-03-31"),
      applicationOpenDate: new Date("2026-01-01"),
      website: "https://www.kcl.ac.uk/study/funding",
      applicationLink: "https://www.kcl.ac.uk/study/funding/scholarships",
      fieldOfStudy: ["All Fields"],
      degreeLevel: [DegreeLevel.MASTER, DegreeLevel.PHD],
      minGPA: 3.3,
      forAfrican: true,
      requiresIELTS: true,
      minIELTS: 6.5,
      numberOfAwards: 18,
      coversTuition: true,
      coversLiving: true,
      featured: true,
      verified: true,
    },
    // More Country-Specific
    {
      name: "Ireland Government Scholarships for African Students",
      provider: "Irish Government",
      country: "Ireland",
      amount: 30000,
      currency: "EUR",
      type: ScholarshipType.FULL,
      description: "Scholarships for African students to pursue higher education in Ireland.",
      eligibility: "Citizens of eligible African countries with outstanding academic records.",
      deadline: new Date("2026-03-31"),
      applicationOpenDate: new Date("2026-01-01"),
      website: "https://www.ireland.ie/en/africa/",
      applicationLink: "https://www.ireland.ie/en/africa/scholarships",
      fieldOfStudy: ["All Fields"],
      degreeLevel: [DegreeLevel.MASTER, DegreeLevel.PHD],
      minGPA: 3.2,
      forAfrican: true,
      requiresIELTS: true,
      minIELTS: 6.5,
      numberOfAwards: 50,
      coversTuition: true,
      coversLiving: true,
      coversTravel: true,
      featured: true,
      verified: true,
    },
    {
      name: "Luxembourg Government Scholarships",
      provider: "Luxembourg Government",
      country: "Luxembourg",
      amount: 28000,
      currency: "EUR",
      type: ScholarshipType.FULL,
      description: "Scholarships for international students to study in Luxembourg.",
      eligibility: "Non-Luxembourg citizens with excellent academic records.",
      deadline: new Date("2026-03-01"),
      applicationOpenDate: new Date("2026-01-01"),
      website: "https://wwwen.uni.lu/students/scholarships",
      applicationLink: "https://wwwen.uni.lu/students/scholarships/apply",
      fieldOfStudy: ["All Fields"],
      degreeLevel: [DegreeLevel.MASTER, DegreeLevel.PHD],
      minGPA: 3.2,
      forAfrican: true,
      requiresIELTS: true,
      minIELTS: 6.5,
      numberOfAwards: 30,
      coversTuition: true,
      coversLiving: true,
      featured: true,
      verified: true,
    },
    {
      name: "Austria Government Scholarships",
      provider: "Austrian Government",
      country: "Austria",
      amount: 30000,
      currency: "EUR",
      type: ScholarshipType.FULL,
      description: "Scholarships for students from developing countries to study in Austria.",
      eligibility: "Citizens of developing countries with outstanding academic achievement.",
      deadline: new Date("2026-02-28"),
      applicationOpenDate: new Date("2025-11-01"),
      website: "https://www.grants.at",
      applicationLink: "https://www.grants.at/apply",
      fieldOfStudy: ["All Fields"],
      degreeLevel: [DegreeLevel.MASTER, DegreeLevel.PHD],
      minGPA: 3.0,
      forAfrican: true,
      requiresIELTS: false,
      numberOfAwards: 200,
      coversTuition: true,
      coversLiving: true,
      coversTravel: true,
      featured: true,
      verified: true,
    },
    // Additional Unique Scholarships
    {
      name: "African Business Education (ABE) Initiative",
      provider: "Japan International Cooperation Agency",
      country: "Japan",
      amount: 40000,
      currency: "USD",
      type: ScholarshipType.FULL,
      description: "Scholarships for young African business leaders to study in Japan.",
      eligibility: "African citizens working in business or government. Age 22-39.",
      deadline: new Date("2026-05-31"),
      applicationOpenDate: new Date("2026-03-01"),
      website: "https://www.jica.go.jp/abe/index.html",
      applicationLink: "https://www.jica.go.jp/abe/apply",
      fieldOfStudy: ["Business", "Economics", "Public Policy"],
      degreeLevel: [DegreeLevel.MASTER],
      minGPA: 3.0,
      minAge: 22,
      maxAge: 39,
      forAfrican: true,
      requiresIELTS: true,
      minIELTS: 6.0,
      numberOfAwards: 200,
      coversTuition: true,
      coversLiving: true,
      coversTravel: true,
      featured: true,
      verified: true,
    },
    {
      name: "African Union - European Union Partnership Scholarships",
      provider: "AU-EU Partnership",
      country: "European Union",
      amount: 35000,
      currency: "EUR",
      type: ScholarshipType.FULL,
      description: "Scholarships for African students to study in EU countries under the AU-EU partnership.",
      eligibility: "Citizens of African Union member states with excellent academic records.",
      deadline: new Date("2026-04-30"),
      applicationOpenDate: new Date("2026-01-01"),
      website: "https://www.africa-eu-partnership.org",
      applicationLink: "https://www.africa-eu-partnership.org/education/scholarships",
      fieldOfStudy: ["All Fields"],
      degreeLevel: [DegreeLevel.MASTER, DegreeLevel.PHD],
      minGPA: 3.2,
      forAfrican: true,
      requiresIELTS: true,
      minIELTS: 6.5,
      numberOfAwards: 100,
      coversTuition: true,
      coversLiving: true,
      coversTravel: true,
      featured: true,
      verified: true,
    },
    {
      name: "African Women in Science and Engineering (AWSE) Fellowship",
      provider: "AWSE Foundation",
      country: "Multiple Countries",
      amount: 30000,
      currency: "USD",
      type: ScholarshipType.FULL,
      description: "Fellowships for African women pursuing careers in science and engineering.",
      eligibility: "African women with outstanding academic records in STEM fields.",
      deadline: new Date("2026-06-30"),
      applicationOpenDate: new Date("2026-01-01"),
      website: "https://www.awse.org",
      applicationLink: "https://www.awse.org/apply",
      fieldOfStudy: ["Engineering", "Science", "Technology", "Mathematics"],
      degreeLevel: [DegreeLevel.MASTER, DegreeLevel.PHD],
      minGPA: 3.3,
      forWomen: true,
      forAfrican: true,
      requiresIELTS: true,
      minIELTS: 6.5,
      numberOfAwards: 40,
      coversTuition: true,
      coversLiving: true,
      featured: true,
      verified: true,
    },
    {
      name: "African Union - China Cooperation Scholarships",
      provider: "AU-China Partnership",
      country: "China",
      amount: 30000,
      currency: "CNY",
      type: ScholarshipType.FULL,
      description: "Scholarships for African students to study in China under AU-China cooperation.",
      eligibility: "Citizens of African Union member states.",
      deadline: new Date("2026-04-30"),
      applicationOpenDate: new Date("2026-01-01"),
      website: "https://www.focac.org",
      applicationLink: "https://www.focac.org/education/scholarships",
      fieldOfStudy: ["All Fields"],
      degreeLevel: [DegreeLevel.MASTER, DegreeLevel.PHD],
      minGPA: 3.0,
      forAfrican: true,
      numberOfAwards: 200,
      coversTuition: true,
      coversLiving: true,
      coversTravel: true,
      featured: true,
      verified: true,
    },
    {
      name: "African Union - India Partnership Scholarships",
      provider: "AU-India Partnership",
      country: "India",
      amount: 20000,
      currency: "INR",
      type: ScholarshipType.FULL,
      description: "Scholarships for African students to study in India.",
      eligibility: "Citizens of African Union member states.",
      deadline: new Date("2026-03-31"),
      applicationOpenDate: new Date("2026-01-01"),
      website: "https://www.iccr.gov.in",
      applicationLink: "https://www.iccr.gov.in/africa",
      fieldOfStudy: ["All Fields"],
      degreeLevel: [DegreeLevel.MASTER, DegreeLevel.PHD],
      minGPA: 3.0,
      forAfrican: true,
      numberOfAwards: 150,
      coversTuition: true,
      coversLiving: true,
      featured: true,
      verified: true,
    },
    // Additional scholarships to reach 100+
    {
      name: "University of Melbourne African Scholarships",
      provider: "University of Melbourne",
      country: "Australia",
      amount: 45000,
      currency: "AUD",
      type: ScholarshipType.FULL,
      description: "Scholarships for outstanding African students to pursue graduate studies at the University of Melbourne.",
      eligibility: "African citizens with exceptional academic achievement.",
      deadline: new Date("2026-10-31"),
      applicationOpenDate: new Date("2026-07-01"),
      website: "https://scholarships.unimelb.edu.au",
      applicationLink: "https://scholarships.unimelb.edu.au/africa",
      fieldOfStudy: ["All Fields"],
      degreeLevel: [DegreeLevel.MASTER, DegreeLevel.PHD],
      minGPA: 3.5,
      forAfrican: true,
      requiresIELTS: true,
      minIELTS: 6.5,
      numberOfAwards: 20,
      coversTuition: true,
      coversLiving: true,
      featured: true,
      verified: true,
    },
    {
      name: "University of Sydney African Excellence Scholarships",
      provider: "University of Sydney",
      country: "Australia",
      amount: 40000,
      currency: "AUD",
      type: ScholarshipType.FULL,
      description: "Scholarships for high-achieving African students at the University of Sydney.",
      eligibility: "African citizens with outstanding academic records.",
      deadline: new Date("2026-09-30"),
      applicationOpenDate: new Date("2026-06-01"),
      website: "https://www.sydney.edu.au/scholarships",
      applicationLink: "https://www.sydney.edu.au/scholarships/africa",
      fieldOfStudy: ["All Fields"],
      degreeLevel: [DegreeLevel.MASTER, DegreeLevel.PHD],
      minGPA: 3.5,
      forAfrican: true,
      requiresIELTS: true,
      minIELTS: 6.5,
      numberOfAwards: 15,
      coversTuition: true,
      coversLiving: true,
      featured: true,
      verified: true,
    },
    {
      name: "University of Amsterdam African Excellence Scholarships",
      provider: "University of Amsterdam",
      country: "Netherlands",
      amount: 30000,
      currency: "EUR",
      type: ScholarshipType.FULL,
      description: "Scholarships for exceptional African students to study at the University of Amsterdam.",
      eligibility: "African citizens with outstanding academic achievement.",
      deadline: new Date("2026-01-15"),
      applicationOpenDate: new Date("2025-10-01"),
      website: "https://www.uva.nl/en/education/master-s/scholarships",
      applicationLink: "https://www.uva.nl/en/education/master-s/scholarships/africa",
      fieldOfStudy: ["All Fields"],
      degreeLevel: [DegreeLevel.MASTER, DegreeLevel.PHD],
      minGPA: 3.3,
      forAfrican: true,
      requiresIELTS: true,
      minIELTS: 6.5,
      numberOfAwards: 12,
      coversTuition: true,
      coversLiving: true,
      featured: true,
      verified: true,
    },
    {
      name: "Leiden University African Excellence Scholarships",
      provider: "Leiden University",
      country: "Netherlands",
      amount: 28000,
      currency: "EUR",
      type: ScholarshipType.FULL,
      description: "Scholarships for outstanding African students at Leiden University.",
      eligibility: "African citizens with excellent academic records.",
      deadline: new Date("2026-02-01"),
      applicationOpenDate: new Date("2025-10-01"),
      website: "https://www.universiteitleiden.nl/en/education/study-programmes/master",
      applicationLink: "https://www.universiteitleiden.nl/en/education/study-programmes/master/scholarships",
      fieldOfStudy: ["All Fields"],
      degreeLevel: [DegreeLevel.MASTER, DegreeLevel.PHD],
      minGPA: 3.3,
      forAfrican: true,
      requiresIELTS: true,
      minIELTS: 6.5,
      numberOfAwards: 10,
      coversTuition: true,
      coversLiving: true,
      featured: true,
      verified: true,
    },
    {
      name: "University of Cape Town Postgraduate Scholarships",
      provider: "University of Cape Town",
      country: "South Africa",
      amount: 25000,
      currency: "ZAR",
      type: ScholarshipType.FULL,
      description: "Scholarships for African students to pursue postgraduate studies at UCT.",
      eligibility: "African citizens with outstanding academic achievement.",
      deadline: new Date("2026-08-31"),
      applicationOpenDate: new Date("2026-04-01"),
      website: "https://www.uct.ac.za/apply/funding/postgraduate",
      applicationLink: "https://www.uct.ac.za/apply/funding/postgraduate/apply",
      fieldOfStudy: ["All Fields"],
      degreeLevel: [DegreeLevel.MASTER, DegreeLevel.PHD],
      minGPA: 3.2,
      forAfrican: true,
      requiresIELTS: true,
      minIELTS: 6.5,
      numberOfAwards: 25,
      coversTuition: true,
      coversLiving: true,
      featured: true,
      verified: true,
    },
    {
      name: "University of Witwatersrand Postgraduate Scholarships",
      provider: "University of Witwatersrand",
      country: "South Africa",
      amount: 22000,
      currency: "ZAR",
      type: ScholarshipType.FULL,
      description: "Scholarships for African students pursuing postgraduate studies at Wits University.",
      eligibility: "African citizens with excellent academic records.",
      deadline: new Date("2026-09-30"),
      applicationOpenDate: new Date("2026-05-01"),
      website: "https://www.wits.ac.za/postgraduate/funding/",
      applicationLink: "https://www.wits.ac.za/postgraduate/funding/apply",
      fieldOfStudy: ["All Fields"],
      degreeLevel: [DegreeLevel.MASTER, DegreeLevel.PHD],
      minGPA: 3.2,
      forAfrican: true,
      requiresIELTS: true,
      minIELTS: 6.5,
      numberOfAwards: 20,
      coversTuition: true,
      coversLiving: true,
      featured: true,
      verified: true,
    },
    {
      name: "African Women in Media (AWIM) Fellowship",
      provider: "African Women in Media",
      country: "Multiple Countries",
      amount: 15000,
      currency: "USD",
      type: ScholarshipType.PARTIAL,
      description: "Fellowships for African women pursuing careers in media and journalism.",
      eligibility: "African women with outstanding academic records in media, journalism, or communications.",
      deadline: new Date("2026-05-31"),
      applicationOpenDate: new Date("2026-01-01"),
      website: "https://www.africanwomeninmedia.com",
      applicationLink: "https://www.africanwomeninmedia.com/fellowships",
      fieldOfStudy: ["Journalism", "Media Studies", "Communications"],
      degreeLevel: [DegreeLevel.MASTER, DegreeLevel.PHD],
      minGPA: 3.0,
      forWomen: true,
      forAfrican: true,
      requiresIELTS: true,
      minIELTS: 6.5,
      numberOfAwards: 30,
      coversTuition: true,
      featured: true,
      verified: true,
    },
    {
      name: "African Leadership Academy (ALA) Scholarships",
      provider: "African Leadership Academy",
      country: "South Africa",
      amount: 75000,
      currency: "USD",
      type: ScholarshipType.FULL,
      description: "Pre-university program preparing the next generation of African leaders.",
      eligibility: "African students aged 15-19 with leadership potential.",
      deadline: new Date("2026-02-15"),
      applicationOpenDate: new Date("2025-09-01"),
      website: "https://www.africanleadershipacademy.org",
      applicationLink: "https://www.africanleadershipacademy.org/apply",
      fieldOfStudy: ["Leadership", "All Fields"],
      degreeLevel: [DegreeLevel.DIPLOMA],
      minGPA: 3.0,
      maxAge: 19,
      minAge: 15,
      forAfrican: true,
      numberOfAwards: 100,
      renewableYears: 2,
      coversTuition: true,
      coversLiving: true,
      coversBooks: true,
      featured: true,
      verified: true,
    },
  ]

  // Check for duplicates and create scholarships
  let created = 0
  let skipped = 0
  
  console.log(`📋 Processing ${additionalScholarships.length} additional scholarships...\n`)
  
  for (const scholarship of additionalScholarships) {
    const isDuplicate = await checkDuplicate(
      scholarship.name,
      scholarship.provider,
      scholarship.website || ''
    )
    
    if (isDuplicate) {
      console.log(`⏭️  Skipped (duplicate): ${scholarship.name}`)
      skipped++
    } else {
      try {
        await prisma.scholarship.create({
          data: scholarship
        })
        console.log(`✅ Created: ${scholarship.name}`)
        created++
      } catch (error: any) {
        console.error(`❌ Error creating ${scholarship.name}:`, error.message)
        skipped++
      }
    }
  }

  // Get final count
  const totalCount = await prisma.scholarship.count()
  
  console.log(`\n🎉 Batch addition completed!`)
  console.log(`✅ Created: ${created} new scholarships`)
  console.log(`⏭️  Skipped: ${skipped} duplicates/errors`)
  console.log(`📊 Total scholarships in database: ${totalCount}`)
  
  if (totalCount >= 100) {
    console.log(`\n🎯 SUCCESS! You now have ${totalCount}+ scholarships!`)
  } else {
    console.log(`\n📈 You need ${100 - totalCount} more scholarships to reach 100+`)
  }
}

main()
  .catch((e) => {
    console.error('❌ Script failed:', e)
    process.exit(1)
  })
  .finally(async () => {
    await prisma.$disconnect()
  })

